spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: toor
    url: jdbc:postgresql://localhost:5432/newFuckUp
  jpa:
    generate-dll: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true